#!/usr/bin/env bash

# Warning: This script will override files!
if [[ "$0" != "./setup" ]]; then
  echo "Error: Must be called from within git repository"
  exit 1
fi

# Sets up the symbolic links
SUBMODULES=$PWD/submodules

link() {
  rm -rf $2
  ln -s $1 $2
}

link $SUBMODULES/.emacs.d/ ~/.emacs.d
link $PWD/tmux.conf ~/.tmux.conf

# Git configuration
git config --global core.excludesfile $PWD/.gitignore_global
git config --global alias.lola "log --graph --decorate --oneline --all"
